### PR TITLE
Further development of main.py (v0.6)

### PR DESCRIPTION
**Pull request by robang74**
I made some changes in several commits in order to be easy to understand and integrate them.

### CODE REVIEW

**Comment by phamngocsonls** [comment]
Thank you. I think no one uses my project. I will check soon

**Comment by robang74** [comment]
> Thank you. I think no one uses my project. I will check soon

It would be nice to add an icon in the task bar that change color depending of the state of connection: gray (no warp), orange (warp) and blue (team cloudflare). Plus, clicking on the icon, the full application is launched or bought to the focus.

What do you think about? My e-mail address should be public on my github homepage. Feel free to use it, as well.

**Comment by phamngocsonls** [comment]
This project was developed when Cloudflare WARP didn't have an official GUI.
My project helps users fix some bugs with GUI. I checked Cloudflare WARP now has an official GUI. We shouldn't update more about my project. Thank you for contributing to my project

**Comment by phamngocsonls** [comment]
I tried Cloudflare WARP GUI. I think it is better than my project

**Pull request merged**
